---
version: '2'
checks:
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
exclude_patterns:
  - bids-validator/versioneer.py
  - bids-validator/bids_validator/_version.py
